---
# This playbook will install Apache and PHP dependencies

- name: Install apache and PHP packages
  action: apt pkg={{ item }} state=present
  with_items:
   - apache2
   - php5
   - libapache2-mod-php5
   - php5-xdebug
   - phpunit

- name: Correctly configure XDebug and Apache
  lineinfile: dest=/etc/php5/apache2/conf.d/20-xdebug.ini line="xdebug.remote_enable = on"
- lineinfile: dest=/etc/php5/apache2/conf.d/20-xdebug.ini line="xdebug.remote_connect_back = on"
- copy: src=000-default dest=/etc/apache2/sites-enabled/000-default owner=www-data group=www-data mode=0600

- name: Enable rewrite module
  apache2_module: state=present name=rewrite

- service: name=apache2 state=reloaded
