---
# This playbook will install SQL and dependencies

- name: Install apache and PHP packages
  action: apt pkg={{ item }} state=present
  with_items:
   - mysql-server
   - php5-mysql
   - python-mysqldb