---
# This playbook will install base software needed to do everything else

- name: Update and upgrade apt
  apt: update_cache=yes
       upgrade=dist
       cache_valid_time=3600

- name: Install base software
  action: apt pkg={{ item }} state=present
  with_items:
   - git

- name: Add github's SSH key
  file: path=/root/.ssh state=directory
- copy: src=known_hosts dest=/root/.ssh/known_hosts owner=root group=root mode=0600 force=no
